// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package easyJSONPackage

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6ab7c85dDecodeExternalModuleV2EasyJSONPackage(in *jlexer.Lexer, out *Example) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Mock":
			out.Mock = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ab7c85dEncodeExternalModuleV2EasyJSONPackage(out *jwriter.Writer, in Example) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Mock\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Mock))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Example) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ab7c85dEncodeExternalModuleV2EasyJSONPackage(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Example) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ab7c85dEncodeExternalModuleV2EasyJSONPackage(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Example) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ab7c85dDecodeExternalModuleV2EasyJSONPackage(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Example) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ab7c85dDecodeExternalModuleV2EasyJSONPackage(l, v)
}
func easyjson6ab7c85dDecodeExternalModuleV2EasyJSONPackage1(in *jlexer.Lexer, out *EasyJSONStruct) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ab7c85dEncodeExternalModuleV2EasyJSONPackage1(out *jwriter.Writer, in EasyJSONStruct) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v EasyJSONStruct) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ab7c85dEncodeExternalModuleV2EasyJSONPackage1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v EasyJSONStruct) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ab7c85dEncodeExternalModuleV2EasyJSONPackage1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *EasyJSONStruct) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ab7c85dDecodeExternalModuleV2EasyJSONPackage1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *EasyJSONStruct) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ab7c85dDecodeExternalModuleV2EasyJSONPackage1(l, v)
}
